### ISSUE TITLE
Moved this source code

### ISSUE THREAD

**Issue by maxehrhardt** [m0rsch1/rock2dot#1]
Hey,

your source code has been refined and used again in the PRL. I just moved it to https://github.com/esa-prl/utils/tree/master/visualization to maintain it better. I hope thats okay for you. 

Greets,
Max

**Comment by m0rsch1** [comment]
Hey Max,

I don't understand the maintenance issue yet. You just could have forked this repo and made a merge request? Apart from that, it is good practice to at least refer to the original code in some way.
If you decide to not fork the original repository, please be so kind and add a link to the original repo.
@levingerdes What do you think?

BR,
Moritz

**Comment by maxehrhardt** [comment]
It was not really meant as an issue, it was just the fastest way to contact you.
And of course I can reference your code.
________________________________

**Comment by levingerdes** [comment]
Hey Moritz,

We figured it would be easier for us to include the script in our [utils repository](https://github.com/esa-prl/utils) rather than keeping it in a separate repository (fork) or submodule (since unfortunately not too many people are comfortable with submodules). The utils repo is where we keep all of the scripts we use in conjunction with the Rock framework, be it for delogging, calibration, and now also the visualization of the connections in Rock scripts.

You are of course right that we should provide a reference to your original repository. Hopefully the changes in the [latest commit](https://github.com/esa-prl/utils/commit/bfacf6ccbb4c4433f0c3897c5b9784fdc25fa02c) are satifactory for you?

Cheers,
Levin

**Comment by m0rsch1** [comment]
Ok,
so let's do the following.
You add me as one of the authors of rock2dot, then I will delete this repository, because it does not make sense to keep an old version of the code then.
What do you think?
BR,
Moritz

**Comment by levingerdes** [comment]
Sure, sounds good. You can also add yourself in a way you see fit (e.g. via __author__ in the script if you like or some other way), you have access to the repository anyways.

Thanks!
Levin
